# Lab 1 - Introduction to NLP

In this lab I check that NLTK works, then download a dataset and look at it with pandas.

## Task 1: choose a dataset type

I chose **CSV**. The dataset is the *IMDB Dataset of 50K Movie Reviews* from Kaggle. Each row is a movie review with a label (positive or negative), so it is a good fit for the sentiment analysis example from the lab.

Libraries used: nltk, pandas, kagglehub. Install them first with `pip install nltk pandas kagglehub ipywidgets` if they are missing.

In [8]:
import warnings
warnings.filterwarnings("ignore")  # hide the tqdm progress bar warning

import os

import nltk
import pandas as pd
import kagglehub

print("NLTK version:", nltk.__version__)

NLTK version: 3.10.3

## Task 2: download and open the dataset

In [9]:
# download the dataset from Kaggle
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)
print(os.listdir(path))

Path to dataset files: C:\Users\GAMING\.cache\kagglehub\datasets\lakshmi25npathi\imdb-dataset-of-50k-movie-reviews\versions\1
['IMDB Dataset.csv']

In [10]:
# load the CSV file in a dataframe
df = pd.read_csv(os.path.join(path, "IMDB Dataset.csv"))

# show the first few rows
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [13]:
# check class distribution
print(df["sentiment"].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64